// <auto-generated />
namespace UserNRolesBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedIdentityFramework : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedIdentityFramework));
        
        string IMigrationMetadata.Id
        {
            get { return "202101102111199_addedIdentityFramework"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
